### ISSUE TITLE
Running tests on the current (3.0.15) does not work

### ISSUE THREAD

**Issue by fbidu** [philsturgeon/build-apis-you-wont-hate#21]
Hello,

Today I found out that running the tests on the chapter5 using the current behat version gives the following error:
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
Unrecognized option "context" under "testwork" 
```
I found out that this is due to some changes on the spec from 2.5.x to 3.x

**Comment by philsturgeon** [comment]
I just changed the reference in the book to install v2.5. I'll look into updating this properly, but its a book and I wrote it a year ago so some code will be using old versions and hopefully people are ok with that.

**Comment by philsturgeon** [comment]
Thanks for reporting this! :D
