### ISSUE TITLE
Doesn't work in PHP 7.2

### ISSUE THREAD

**Issue by nikolayandreev** [philsturgeon/build-apis-you-wont-hate#24]
I use Homestead and in PHP 7.2 it doesn't even have Mcrypt

When I try to access the "dev.book6.local" url that I've configured in Homestead and host file, I get:
Mcrypt PHP extension required.

Same thing on php artisan.

**Comment by philsturgeon** [comment]
I would not expect code to last forever without any changes whatsoever. :)

There are no plans to keep updating the source code for new major versions of laravel or PHP or anything else. You can run this locally with PHP56 and it'll work fine.
